version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: projectmanager-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1.048596Gate"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "1.048596Gate", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 3s
      retries: 10

  web:
    build:
      context: ./ProjectManager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProjectDb;User Id=sa;Password=1.048596Gate;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  mssql_data: